apiVersion: tpu.gcp-beta.m.upbound.io/v1beta1
kind: V2VM
metadata:
  name: tpu
  namespace: upbound-system
spec:
  forProvider:
    zone: europe-west4-b
    runtimeVersion: "tpu-ubuntu2204-base"
    acceleratorConfig:
      topology: 2x2x1
      type: V5P
    networkConfig:
      network: default
      subnetwork: default
      enableExternalIps: true

  providerConfigRef:
    kind: ClusterProviderConfig
    name: default
